apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-mario-deployment
spec:
  replicas: 2  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: super-mario-container
        image: kessie/super-mario:latest 
        ports:
        - containerPort: 80
